"""create initial domain tables

Revision ID: c303e69e3f4e
Revises: 
Create Date: 2026-04-23 22:18:11.397396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c303e69e3f4e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    if bind.dialect.name == "sqlite":
        pk_type = sa.Integer()
        fk_type = sa.Integer()
    else:
        pk_type = sa.BigInteger()
        fk_type = sa.BigInteger()

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', pk_type, autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('streaming_service',
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('keyword_patterns', sa.JSON(), nullable=True),
    sa.Column('id', pk_type, autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', name='uq_streaming_services_slug')
    )
    op.create_table('customer',
    sa.Column('entity_id', fk_type, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('whatsapp_e164', sa.String(length=32), nullable=False),
    sa.Column('id', pk_type, autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_id', 'whatsapp_e164', name='uq_customers_entity_whatsapp_e164')
    )
    op.create_index(op.f('ix_customer_entity_id'), 'customer', ['entity_id'], unique=False)
    op.create_table('streaming_account',
    sa.Column('entity_id', fk_type, nullable=False),
    sa.Column('streaming_service_id', fk_type, nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', pk_type, autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['streaming_service_id'], ['streaming_service.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_id', 'streaming_service_id', 'label', name='uq_streaming_accounts_entity_service_label')
    )
    op.create_index(op.f('ix_streaming_account_entity_id'), 'streaming_account', ['entity_id'], unique=False)
    op.create_index(op.f('ix_streaming_account_streaming_service_id'), 'streaming_account', ['streaming_service_id'], unique=False)
    op.create_table('user',
    sa.Column('entity_id', fk_type, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('supertokens_user_id', sa.String(length=255), nullable=False),
    sa.Column('id', pk_type, autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('supertokens_user_id', name='uq_users_supertokens_user_id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    op.create_index(op.f('ix_user_entity_id'), 'user', ['entity_id'], unique=False)
    op.create_table('customer_streaming_entitlement',
    sa.Column('customer_id', fk_type, nullable=False),
    sa.Column('streaming_service_id', fk_type, nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', pk_type, autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['streaming_service_id'], ['streaming_service.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', 'streaming_service_id', name='uq_customer_streaming_entitlements_customer_service')
    )
    op.create_index(op.f('ix_customer_streaming_entitlement_customer_id'), 'customer_streaming_entitlement', ['customer_id'], unique=False)
    op.create_index(op.f('ix_customer_streaming_entitlement_streaming_service_id'), 'customer_streaming_entitlement', ['streaming_service_id'], unique=False)
    op.create_table('mailbox_credential',
    sa.Column('streaming_account_id', fk_type, nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('mailbox_address', sa.String(length=320), nullable=False),
    sa.Column('credential_payload', sa.JSON(), nullable=True),
    sa.Column('secret_ref', sa.String(length=512), nullable=True),
    sa.Column('token_scopes', sa.String(length=2048), nullable=True),
    sa.Column('token_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', pk_type, autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['streaming_account_id'], ['streaming_account.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mailbox_credential_streaming_account_id'), 'mailbox_credential', ['streaming_account_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mailbox_credential_streaming_account_id'), table_name='mailbox_credential')
    op.drop_table('mailbox_credential')
    op.drop_index(op.f('ix_customer_streaming_entitlement_streaming_service_id'), table_name='customer_streaming_entitlement')
    op.drop_index(op.f('ix_customer_streaming_entitlement_customer_id'), table_name='customer_streaming_entitlement')
    op.drop_table('customer_streaming_entitlement')
    op.drop_index(op.f('ix_user_entity_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_streaming_account_streaming_service_id'), table_name='streaming_account')
    op.drop_index(op.f('ix_streaming_account_entity_id'), table_name='streaming_account')
    op.drop_table('streaming_account')
    op.drop_index(op.f('ix_customer_entity_id'), table_name='customer')
    op.drop_table('customer')
    op.drop_table('streaming_service')
    op.drop_table('entity')
    # ### end Alembic commands ###
